version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: dynbit/alpine-docker-make-git:latest
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Build & Upload alpine-docker-make-git
          command:
            make alpine-docker-make-git
      - run:
          name: Build & Upload golang-git-make-dep-npm
          command:
            make golang-git-make-dep-npm
      - run:
          name: Build & Upload golang-eddy
          command:
            make golang-eddy

